FROM node:lts-alpine AS builder
WORKDIR /app

COPY ./FE/package*.json ./
RUN npm install

COPY ./FE ./
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY ./FE/nginx.conf /etc/nginx/conf.d/test.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
